"""
ARISE Demo Voiceover Generator
Generates individual MP3 clips for each script line using edge-tts,
then merges them with 800ms silence gaps into voiceover_full.mp3

Run: python generate_voiceover.py

Requirements (install once):
  pip install edge-tts pydub

Note: pydub also needs ffmpeg. If you get an ffmpeg error:
  Download from https://ffmpeg.org/download.html and add to PATH
  OR install via: winget install ffmpeg
"""

import asyncio
import os
import sys

# ── Script lines: (number, narration_text) ──────────────────────────────────
LINES = [
    (1,  "Introducing ARISE — India's first AI-powered Crime Intelligence Platform, built for the State Crime Records Bureau of Karnataka."),
    (2,  "Everything you are about to see is real. The data displayed in every module is live data, stored in Zoho Catalyst's DataStore across ten production ZCQL tables — including FIR master, offender profiles, geospatial hotspot indicators, modus operandi signatures, and BSA audit trails."),
    (3,  "ARISE transforms raw FIR data into actionable intelligence — combining real-time analytics, geospatial mapping, and artificial intelligence to help law enforcement make faster, smarter decisions."),
    (4,  "This is the Command Center — the nerve center of ARISE. At a glance, officers see total cases, forensic cases, open cases, and repeat offenders across the state. These numbers are queried live from the ZCQL database every time the dashboard loads."),
    (5,  "The AI anomaly detection system automatically flags unusual patterns — like a cluster of armed robberies between 3 and 4 AM in a specific zone. This alert was generated by the automated Catalyst job scheduler, not manually entered."),
    (6,  "Crime trends are visualized by district and by BNS section — directly aggregated from the fir master table. Every bar on this chart represents real FIR registrations, grouped and counted in real time."),
    (7,  "The Zia voice assistant sits at the heart of the command center, powered by Zoho Catalyst's GLM large language model, ready to answer natural language queries about real crime data."),
    (8,  "The Crime Analytics module provides deep-dive visualizations — district-wise breakdowns, section-wise case distributions, and temporal crime patterns. All sourced from the modus operandi signature table in the live database."),
    (9,  "The Geospatial Intelligence module features a 3D globe and 2D map with AI-generated risk zones. Each zone is drawn from the geospatial hotspot indicator table — containing composite risk scores, predicted peak hours, and crime density computed from actual FIR coordinates."),
    (10, "Now here is something important. Any police station running CCTNS — the Crime and Criminal Tracking Network — can push their FIR data directly into ARISE using a secure webhook. The Settings page contains the full webhook URL and authentication token. One POST request from the station's system and the data appears here instantly."),
    (11, "Network Analysis uses graph intelligence to map relationships between criminals. Every node and edge in this graph comes from the entity association graph table — capturing co-accused links, handler relationships, financial conduits, and AI-discovered connections extracted from FIR narratives."),
    (12, "Offender Intelligence provides comprehensive criminal profiles — bail status from the bail custody status table, modus operandi from the modus operandi signature table, and recidivism risk scores computed by the QuickML model running on Zoho Catalyst."),
    (13, "The Predictions module uses machine learning to forecast emerging crime hotspots. The forecast data and anomaly scores are stored in real ZCQL tables and updated by the Catalyst job scheduler on a scheduled basis."),
    (14, "Socio-demographic insights correlate crime data with population density, literacy rates, unemployment proxies, and economic stress indicators — drawn directly from the geospatial hotspot indicator table which includes socioeconomic vulnerability scores per grid cell."),
    (15, "The AI Assistant is powered by Zoho Catalyst's GLM large language model with Retrieval Augmented Generation. When an officer asks a question, the system queries the live ZCQL tables, injects the retrieved records into the prompt, and every answer cites the exact FIR UID or offender UID from the database. No hallucinations — just verified data."),
    (16, "Search and Investigation allows officers to run cross-database queries across FIRs, accused persons, and case details with intelligent fuzzy matching — all backed by live ZCQL queries."),
    (17, "The Zia Face Analytics module enables officers to upload a suspect photograph and receive AI-powered facial attribute analysis using Zoho's computer vision engine, cross-referenced against the biometric records table."),
    (18, "The Reports module generates professional documents with AI-powered explainability. Every report is backed by SHA-256 integrity hashes stored in the BSA audit trail table — making each report legally admissible under BSA Section 63."),
    (19, "Governance provides BNSS compliance tracking, chargesheet deadline monitoring, and tamper-evident audit logs — all written to the BSA audit trail table with server-side timestamps from Zoho Catalyst's infrastructure."),
    (20, "ARISE supports full Kannada localization — every label, chart, and AI response can be switched to the regional language. And through the Settings page, any police station can register their CCTNS webhook endpoint, obtain their push token, and begin streaming live FIR data into the platform within minutes."),
    (21, "ARISE. Not a prototype. Not simulated data. A production-grade intelligence platform running on Zoho Catalyst — with real ZCQL tables, real AI models, and a real pathway for every police station in Karnataka to connect through CCTNS webhooks. Augmented intelligence. Real-time insights. Safer communities."),
]

VOICE       = "en-US-AvaNeural"
RATE        = "-5%"          # slightly slower = more natural for demos
OUTPUT_DIR  = "voiceover_clips"
MERGED_FILE = "voiceover_full.mp3"
SILENCE_GAP = 800            # ms gap between lines

# ── Step 1: generate individual clips ────────────────────────────────────────

async def generate_clip(line_num, text):
    try:
        import edge_tts
    except ImportError:
        print("ERROR: edge-tts not installed. Run: pip install edge-tts")
        sys.exit(1)

    out_path = os.path.join(OUTPUT_DIR, f"line_{line_num:02d}.mp3")
    if os.path.exists(out_path):
        print(f"  [SKIP] line_{line_num:02d}.mp3 already exists")
        return out_path

    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
    await communicate.save(out_path)
    print(f"  [OK]   line_{line_num:02d}.mp3 — {len(text)} chars")
    return out_path


async def generate_all():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"\n=== Generating {len(LINES)} voice clips ===")
    print(f"Voice: {VOICE}  |  Rate: {RATE}\n")
    
    clip_paths = []
    for num, text in LINES:
        path = await generate_clip(num, text)
        clip_paths.append(path)
    
    return clip_paths


# ── Step 2: merge with silence gaps ──────────────────────────────────────────

def merge_clips(clip_paths):
    try:
        from pydub import AudioSegment
    except ImportError:
        print("\nWARNING: pydub not installed — skipping merge.")
        print("Install with: pip install pydub")
        print("Individual clips are ready in:", OUTPUT_DIR)
        return

    print(f"\n=== Merging {len(clip_paths)} clips with {SILENCE_GAP}ms gaps ===")

    silence = AudioSegment.silent(duration=SILENCE_GAP)
    combined = AudioSegment.empty()

    for i, path in enumerate(clip_paths):
        try:
            seg = AudioSegment.from_mp3(path)
            combined += seg
            if i < len(clip_paths) - 1:
                combined += silence
            line_num = i + 1
            print(f"  [+] line_{line_num:02d}.mp3  ({len(seg) / 1000:.1f}s)")
        except Exception as e:
            print(f"  [WARN] Could not load {path}: {e}")

    total_sec = len(combined) / 1000
    combined.export(MERGED_FILE, format="mp3")
    print(f"\n[DONE] {MERGED_FILE} — Total duration: {total_sec:.1f}s ({total_sec/60:.1f} min)")
    print(f"       Individual clips: {OUTPUT_DIR}/")


# ── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    clip_paths = asyncio.run(generate_all())
    merge_clips(clip_paths)
    print("\nVoiceover generation complete.")
